services:
  email-service:
    build:
      context: ./email
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env