apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: microservices
build:
  artifacts:
    - image: email-service
      context: ./email
      docker:
        dockerfile: Dockerfile
    - image: user-service
      context: ./user
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/email-deployment.yaml
      - k8s/email-configmap.yaml
      - k8s/email-secrets.yaml
      - k8s/user-deployment.yaml
      - k8s/user-configmap.yaml
      - k8s/user-secrets.yaml
portForward:
  - resourceType: service
    resourceName: email-service
    namespace: default
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: user-service
    namespace: default
    port: 8081
    localPort: 8081
