apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: email-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: SERVER_PORT
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: DB_URL
            - name: SPRING_RABBITMQ_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: SPRING_RABBITMQ_ADDRESS
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: MAIL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080