apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SERVER_PORT
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: DB_URL
            - name: SPRING_RABBITMQ_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_RABBITMQ_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081