name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonar:
    name: Build & Sonar — ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ email, user ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles(format('{0}/pom.xml', matrix.module)) }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build & analyze "${{ matrix.module }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B \
            -f ${{ matrix.module }}/pom.xml \
            verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=thiago-abarros_${{ matrix.module }} \
            -Dsonar.projectName="${{ matrix.module }}-service" \
            -Dsonar.sources=src/main/java

